apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jaeger-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-jaeger
      protocol: HTTP
    hosts:
    - "jaeger.INGRESS_DOMAIN"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-vs
spec:
  hosts:
  - "jaeger.INGRESS_DOMAIN"
  gateways:
  - jaeger-gateway
  http:
  - route:
    - destination:
        host: jaeger
        port:
          number: 16686