apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: media-frontend-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 8081
        name: http-media-frontend
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: media-frontend-vs
spec:
  hosts:
    - "*"
  gateways:
    - media-frontend-gateway
  http:
    - route:
        - destination:
            host: media-frontend
            port:
              number: 8081
