# apiVersion: v1
# kind: ConfigMap
# metadata:
#   namespace: metallb-system
#   name: config
# data:
#   config: |
#     address-pools:
#     - name: default
#       protocol: layer2
#       addresses:
#       - 10.64.82.240-10.64.82.250
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addr-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.64.82.240-10.64.82.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-addr-pool