apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: media-microservices-jaeger-gateway
  namespace: media-microservices
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 16687
        name: http-media-microservices-jaeger
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: media-microservices-jaeger-vs
  namespace: media-microservices
spec:
  hosts:
    - "*"
  gateways:
    - media-microservices-jaeger-gateway
  http:
    - route:
        - destination:
            host: jaeger
            port:
              number: 16686
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: media-microservices-jaeger
  namespace: media-microservices
spec:
  host: jaeger
  trafficPolicy:
    tls:
      mode: DISABLE
---
