apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-web-server-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 8080
        name: http-nginx-web-server
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-web-server-vs
spec:
  hosts:
    - "*"
  gateways:
    - nginx-web-server-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: nginx-web-server
          port:
            number: 8080
